# Generated by Django 6.0.6 on 2026-06-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
